### ISSUE TITLE
Failed to run make

### ISSUE THREAD

**Issue by rizmut** [subuk/awx-rpm#7]
```
make: stat: Makefile: Permission denied
make: *** No rule to make target `sdist'.  Stop.
```

What's wrong?

**Comment by subuk** [comment]
Could you provide full output and command, which leads to this error?

**Comment by subuk** [comment]
Okay, I found the problem, it relates to #5. Build process of awx project has been changed a bit.

**Comment by subuk** [comment]
Nope, it is not related. I tried to build latest awx sources and it worked fine. I think you just copied all code block under 'How to build source archive'. So I fixed it, try on more time, please: https://github.com/subuk/awx-rpm/commit/3ccc7b58e133fc85b01a64fc73fed961f5ef1539

**Comment by rizmut** [comment]
`[root@someserver ~]# docker run -v `pwd`:/awx --rm -i centos:7 /bin/bash <<EOF
> yum install -y epel-release && yum install -y bzip2 gcc-c++ git gettext make python-pip
> curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
> yum install -y nodejs
> cd /awx/
> make sdist
> EOF
/usr/bin/docker-current: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See '/usr/bin/docker-current run --help'.
[root@awx-rpm-server ~]# systemctl start docker
[root@awx-rpm-server ~]# docker run -v `pwd`:/awx --rm -i centos:7 /bin/bash <<EOF
> yum install -y epel-release && yum install -y bzip2 gcc-c++ git gettext make python-pip
> curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
> yum install -y nodejs
> cd /awx/
> make sdist
> EOF
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: repo.apiknet.co.id
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-9 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                Arch             Version         Repository        Size
================================================================================
Installing:
 epel-release           noarch           7-9             extras            14 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 14 k
Installed size: 24 k
Downloading packages:
warning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-9.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for epel-release-7-9.noarch.rpm is not installed
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : epel-release-7-9.noarch                                      1/1 
  Verifying  : epel-release-7-9.noarch                                      1/1 

Installed:
  epel-release.noarch 0:7-9                                                     

Complete!
Loaded plugins: fastestmirror, ovl
http://mirror.nes.co.id/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
http://fedora.dionipe.id/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/7/x86_64/repodata/536e0b432d4bf1392333b11f37d7d023cf71edf8ee19039ce64f76783a366876-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

Loading mirror speeds from cached hostfile
 * base: repo.apiknet.co.id
 * epel: mirror.nes.co.id
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
Resolving Dependencies
--> Running transaction check
---> Package bzip2.x86_64 0:1.0.6-13.el7 will be installed
---> Package gcc-c++.x86_64 0:4.8.5-16.el7 will be installed
--> Processing Dependency: libstdc++-devel = 4.8.5-16.el7 for package: gcc-c++-4.8.5-16.el7.x86_64
--> Processing Dependency: gcc = 4.8.5-16.el7 for package: gcc-c++-4.8.5-16.el7.x86_64
--> Processing Dependency: libmpfr.so.4()(64bit) for package: gcc-c++-4.8.5-16.el7.x86_64
--> Processing Dependency: libmpc.so.3()(64bit) for package: gcc-c++-4.8.5-16.el7.x86_64
---> Package gettext.x86_64 0:0.19.8.1-2.el7 will be installed
--> Processing Dependency: gettext-libs(x86-64) = 0.19.8.1-2.el7 for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libgomp.so.1(GOMP_1.0)(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libunistring.so.0()(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libgomp.so.1()(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libgettextsrc-0.19.8.1.so()(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libgettextlib-0.19.8.1.so()(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
--> Processing Dependency: libcroco-0.6.so.3()(64bit) for package: gettext-0.19.8.1-2.el7.x86_64
---> Package git.x86_64 0:1.8.3.1-12.el7_4 will be installed
--> Processing Dependency: perl-Git = 1.8.3.1-12.el7_4 for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl >= 5.008 for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: rsync for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(warnings) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(vars) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(strict) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(lib) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(Term::ReadKey) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(Git) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(Getopt::Long) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::stat) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Temp) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Spec) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Path) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Find) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Copy) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(File::Basename) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(Exporter) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: perl(Error) for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: openssh-clients for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: less for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: /usr/bin/perl for package: git-1.8.3.1-12.el7_4.x86_64
--> Processing Dependency: libgnome-keyring.so.0()(64bit) for package: git-1.8.3.1-12.el7_4.x86_64
---> Package make.x86_64 1:3.82-23.el7 will be installed
---> Package python2-pip.noarch 0:8.1.2-5.el7 will be installed
--> Processing Dependency: python-setuptools for package: python2-pip-8.1.2-5.el7.noarch
--> Running transaction check
---> Package gcc.x86_64 0:4.8.5-16.el7 will be installed
--> Processing Dependency: cpp = 4.8.5-16.el7 for package: gcc-4.8.5-16.el7.x86_64
--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-16.el7.x86_64
---> Package gettext-libs.x86_64 0:0.19.8.1-2.el7 will be installed
---> Package less.x86_64 0:458-9.el7 will be installed
--> Processing Dependency: groff-base for package: less-458-9.el7.x86_64
---> Package libcroco.x86_64 0:0.6.11-1.el7 will be installed
---> Package libgnome-keyring.x86_64 0:3.12.0-1.el7 will be installed
---> Package libgomp.x86_64 0:4.8.5-16.el7 will be installed
---> Package libmpc.x86_64 0:1.0.1-3.el7 will be installed
---> Package libstdc++-devel.x86_64 0:4.8.5-16.el7 will be installed
---> Package libunistring.x86_64 0:0.9.3-9.el7 will be installed
---> Package mpfr.x86_64 0:3.1.1-4.el7 will be installed
---> Package openssh-clients.x86_64 0:7.4p1-13.el7_4 will be installed
--> Processing Dependency: openssh = 7.4p1-13.el7_4 for package: openssh-clients-7.4p1-13.el7_4.x86_64
--> Processing Dependency: fipscheck-lib(x86-64) >= 1.3.0 for package: openssh-clients-7.4p1-13.el7_4.x86_64
--> Processing Dependency: libfipscheck.so.1()(64bit) for package: openssh-clients-7.4p1-13.el7_4.x86_64
--> Processing Dependency: libedit.so.0()(64bit) for package: openssh-clients-7.4p1-13.el7_4.x86_64
---> Package perl.x86_64 4:5.16.3-292.el7 will be installed
--> Processing Dependency: perl-libs = 4:5.16.3-292.el7 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Socket) >= 1.3 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) >= 1.10 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl-macros for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl-libs for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads::shared) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(constant) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::Local) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Storable) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Socket) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::XHTML) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::Search) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Filter::Util::Call) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Carp) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: libperl.so()(64bit) for package: 4:perl-5.16.3-292.el7.x86_64
---> Package perl-Error.noarch 1:0.17020-2.el7 will be installed
---> Package perl-Exporter.noarch 0:5.68-3.el7 will be installed
---> Package perl-File-Path.noarch 0:2.09-2.el7 will be installed
---> Package perl-File-Temp.noarch 0:0.23.01-3.el7 will be installed
---> Package perl-Getopt-Long.noarch 0:2.40-2.el7 will be installed
--> Processing Dependency: perl(Pod::Usage) >= 1.14 for package: perl-Getopt-Long-2.40-2.el7.noarch
--> Processing Dependency: perl(Text::ParseWords) for package: perl-Getopt-Long-2.40-2.el7.noarch
---> Package perl-Git.noarch 0:1.8.3.1-12.el7_4 will be installed
---> Package perl-PathTools.x86_64 0:3.40-5.el7 will be installed
---> Package perl-TermReadKey.x86_64 0:2.30-20.el7 will be installed
---> Package python-setuptools.noarch 0:0.9.8-7.el7 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-setuptools-0.9.8-7.el7.noarch
---> Package rsync.x86_64 0:3.0.9-18.el7 will be installed
--> Running transaction check
---> Package cpp.x86_64 0:4.8.5-16.el7 will be installed
---> Package fipscheck-lib.x86_64 0:1.4.1-6.el7 will be installed
--> Processing Dependency: /usr/bin/fipscheck for package: fipscheck-lib-1.4.1-6.el7.x86_64
---> Package glibc-devel.x86_64 0:2.17-196.el7 will be installed
--> Processing Dependency: glibc-headers = 2.17-196.el7 for package: glibc-devel-2.17-196.el7.x86_64
--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-196.el7.x86_64
---> Package groff-base.x86_64 0:1.22.2-8.el7 will be installed
---> Package libedit.x86_64 0:3.0-12.20121213cvs.el7 will be installed
---> Package openssh.x86_64 0:7.4p1-13.el7_4 will be installed
---> Package perl-Carp.noarch 0:1.26-244.el7 will be installed
---> Package perl-Filter.x86_64 0:1.49-3.el7 will be installed
---> Package perl-Pod-Simple.noarch 1:3.28-4.el7 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
--> Processing Dependency: perl(Encode) for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
---> Package perl-Pod-Usage.noarch 0:1.63-3.el7 will be installed
--> Processing Dependency: perl(Pod::Text) >= 3.15 for package: perl-Pod-Usage-1.63-3.el7.noarch
--> Processing Dependency: perl-Pod-Perldoc for package: perl-Pod-Usage-1.63-3.el7.noarch
---> Package perl-Scalar-List-Utils.x86_64 0:1.27-248.el7 will be installed
---> Package perl-Socket.x86_64 0:2.010-4.el7 will be installed
---> Package perl-Storable.x86_64 0:2.45-3.el7 will be installed
---> Package perl-Text-ParseWords.noarch 0:3.29-4.el7 will be installed
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
---> Package perl-Time-Local.noarch 0:1.2300-2.el7 will be installed
---> Package perl-constant.noarch 0:1.27-2.el7 will be installed
---> Package perl-libs.x86_64 4:5.16.3-292.el7 will be installed
---> Package perl-macros.x86_64 4:5.16.3-292.el7 will be installed
---> Package perl-threads.x86_64 0:1.87-4.el7 will be installed
---> Package perl-threads-shared.x86_64 0:1.43-6.el7 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el7 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
--> Running transaction check
---> Package fipscheck.x86_64 0:1.4.1-6.el7 will be installed
---> Package glibc-headers.x86_64 0:2.17-196.el7 will be installed
--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-196.el7.x86_64
--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-196.el7.x86_64
---> Package perl-Encode.x86_64 0:2.51-7.el7 will be installed
---> Package perl-Pod-Escapes.noarch 1:1.04-292.el7 will be installed
---> Package perl-Pod-Perldoc.noarch 0:3.20-4.el7 will be installed
--> Processing Dependency: perl(parent) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: perl(HTTP::Tiny) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
---> Package perl-podlators.noarch 0:2.5.1-3.el7 will be installed
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
--> Running transaction check
---> Package kernel-headers.x86_64 0:3.10.0-693.5.2.el7 will be installed
---> Package perl-HTTP-Tiny.noarch 0:0.033-3.el7 will be installed
---> Package perl-parent.noarch 1:0.225-244.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                            Arch   Version                Repository
                                                                           Size
================================================================================
Installing:
 bzip2                              x86_64 1.0.6-13.el7           base     52 k
 gcc-c++                            x86_64 4.8.5-16.el7           base    7.2 M
 gettext                            x86_64 0.19.8.1-2.el7         base    1.0 M
 git                                x86_64 1.8.3.1-12.el7_4       updates 4.4 M
 make                               x86_64 1:3.82-23.el7          base    420 k
 python2-pip                        noarch 8.1.2-5.el7            epel    1.7 M
Installing for dependencies:
 cpp                                x86_64 4.8.5-16.el7           base    5.9 M
 fipscheck                          x86_64 1.4.1-6.el7            base     21 k
 fipscheck-lib                      x86_64 1.4.1-6.el7            base     11 k
 gcc                                x86_64 4.8.5-16.el7           base     16 M
 gettext-libs                       x86_64 0.19.8.1-2.el7         base    501 k
 glibc-devel                        x86_64 2.17-196.el7           base    1.1 M
 glibc-headers                      x86_64 2.17-196.el7           base    675 k
 groff-base                         x86_64 1.22.2-8.el7           base    942 k
 kernel-headers                     x86_64 3.10.0-693.5.2.el7     updates 6.0 M
 less                               x86_64 458-9.el7              base    120 k
 libcroco                           x86_64 0.6.11-1.el7           base    105 k
 libedit                            x86_64 3.0-12.20121213cvs.el7 base     92 k
 libgnome-keyring                   x86_64 3.12.0-1.el7           base    109 k
 libgomp                            x86_64 4.8.5-16.el7           base    154 k
 libmpc                             x86_64 1.0.1-3.el7            base     51 k
 libstdc++-devel                    x86_64 4.8.5-16.el7           base    1.5 M
 libunistring                       x86_64 0.9.3-9.el7            base    293 k
 mpfr                               x86_64 3.1.1-4.el7            base    203 k
 openssh                            x86_64 7.4p1-13.el7_4         updates 509 k
 openssh-clients                    x86_64 7.4p1-13.el7_4         updates 654 k
 perl                               x86_64 4:5.16.3-292.el7       base    8.0 M
 perl-Carp                          noarch 1.26-244.el7           base     19 k
 perl-Encode                        x86_64 2.51-7.el7             base    1.5 M
 perl-Error                         noarch 1:0.17020-2.el7        base     32 k
 perl-Exporter                      noarch 5.68-3.el7             base     28 k
 perl-File-Path                     noarch 2.09-2.el7             base     26 k
 perl-File-Temp                     noarch 0.23.01-3.el7          base     56 k
 perl-Filter                        x86_64 1.49-3.el7             base     76 k
 perl-Getopt-Long                   noarch 2.40-2.el7             base     56 k
 perl-Git                           noarch 1.8.3.1-12.el7_4       updates  53 k
 perl-HTTP-Tiny                     noarch 0.033-3.el7            base     38 k
 perl-PathTools                     x86_64 3.40-5.el7             base     82 k
 perl-Pod-Escapes                   noarch 1:1.04-292.el7         base     51 k
 perl-Pod-Perldoc                   noarch 3.20-4.el7             base     87 k
 perl-Pod-Simple                    noarch 1:3.28-4.el7           base    216 k
 perl-Pod-Usage                     noarch 1.63-3.el7             base     27 k
 perl-Scalar-List-Utils             x86_64 1.27-248.el7           base     36 k
 perl-Socket                        x86_64 2.010-4.el7            base     49 k
 perl-Storable                      x86_64 2.45-3.el7             base     77 k
 perl-TermReadKey                   x86_64 2.30-20.el7            base     31 k
 perl-Text-ParseWords               noarch 3.29-4.el7             base     14 k
 perl-Time-HiRes                    x86_64 4:1.9725-3.el7         base     45 k
 perl-Time-Local                    noarch 1.2300-2.el7           base     24 k
 perl-constant                      noarch 1.27-2.el7             base     19 k
 perl-libs                          x86_64 4:5.16.3-292.el7       base    688 k
 perl-macros                        x86_64 4:5.16.3-292.el7       base     43 k
 perl-parent                        noarch 1:0.225-244.el7        base     12 k
 perl-podlators                     noarch 2.5.1-3.el7            base    112 k
 perl-threads                       x86_64 1.87-4.el7             base     49 k
 perl-threads-shared                x86_64 1.43-6.el7             base     39 k
 python-backports                   x86_64 1.0-8.el7              base    5.8 k
 python-backports-ssl_match_hostname
                                    noarch 3.4.0.2-4.el7          base     12 k
 python-setuptools                  noarch 0.9.8-7.el7            base    397 k
 rsync                              x86_64 3.0.9-18.el7           base    360 k

Transaction Summary
================================================================================
Install  6 Packages (+54 Dependent packages)

Total download size: 62 M
Installed size: 170 M
Downloading packages:
http://mirror.nus.edu.sg/centos/7.4.1708/os/x86_64/Packages/fipscheck-1.4.1-6.el7.x86_64.rpm: [Errno 14] curl#18 - "transfer closed with 13545 bytes remaining to read"
Trying other mirror.
http://sumberterbuka.beritagar.id/centos/7.4.1708/os/x86_64/Packages/fipscheck-1.4.1-6.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=base clean metadata
Trying other mirror.
Public key for python2-pip-8.1.2-5.el7.noarch.rpm is not installed
warning: /var/cache/yum/x86_64/7/epel/packages/python2-pip-8.1.2-5.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
--------------------------------------------------------------------------------
Total                                              2.5 MB/s |  62 MB  00:25     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-9.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : mpfr-3.1.1-4.el7.x86_64                                     1/60 
  Installing : libmpc-1.0.1-3.el7.x86_64                                   2/60 
  Installing : fipscheck-1.4.1-6.el7.x86_64                                3/60 
  Installing : fipscheck-lib-1.4.1-6.el7.x86_64                            4/60 
  Installing : libgomp-4.8.5-16.el7.x86_64                                 5/60 
  Installing : libcroco-0.6.11-1.el7.x86_64                                6/60 
  Installing : groff-base-1.22.2-8.el7.x86_64                              7/60 
  Installing : libunistring-0.9.3-9.el7.x86_64                             8/60 
  Installing : gettext-libs-0.19.8.1-2.el7.x86_64                          9/60 
  Installing : 1:perl-parent-0.225-244.el7.noarch                         10/60 
  Installing : perl-HTTP-Tiny-0.033-3.el7.noarch                          11/60 
  Installing : perl-podlators-2.5.1-3.el7.noarch                          12/60 
  Installing : perl-Pod-Perldoc-3.20-4.el7.noarch                         13/60 
  Installing : perl-Text-ParseWords-3.29-4.el7.noarch                     14/60 
  Installing : 1:perl-Pod-Escapes-1.04-292.el7.noarch                     15/60 
  Installing : perl-Encode-2.51-7.el7.x86_64                              16/60 
  Installing : perl-Pod-Usage-1.63-3.el7.noarch                           17/60 
  Installing : 4:perl-macros-5.16.3-292.el7.x86_64                        18/60 
  Installing : 4:perl-libs-5.16.3-292.el7.x86_64                          19/60 
  Installing : 4:perl-Time-HiRes-1.9725-3.el7.x86_64                      20/60 
  Installing : perl-threads-1.87-4.el7.x86_64                             21/60 
  Installing : perl-Socket-2.010-4.el7.x86_64                             22/60 
  Installing : perl-Carp-1.26-244.el7.noarch                              23/60 
  Installing : perl-Storable-2.45-3.el7.x86_64                            24/60 
  Installing : perl-threads-shared-1.43-6.el7.x86_64                      25/60 
  Installing : perl-PathTools-3.40-5.el7.x86_64                           26/60 
  Installing : perl-Scalar-List-Utils-1.27-248.el7.x86_64                 27/60 
  Installing : perl-Exporter-5.68-3.el7.noarch                            28/60 
  Installing : perl-Time-Local-1.2300-2.el7.noarch                        29/60 
  Installing : perl-constant-1.27-2.el7.noarch                            30/60 
  Installing : perl-File-Temp-0.23.01-3.el7.noarch                        31/60 
  Installing : perl-File-Path-2.09-2.el7.noarch                           32/60 
  Installing : perl-Filter-1.49-3.el7.x86_64                              33/60 
  Installing : 1:perl-Pod-Simple-3.28-4.el7.noarch                        34/60 
  Installing : perl-Getopt-Long-2.40-2.el7.noarch                         35/60 
  Installing : 4:perl-5.16.3-292.el7.x86_64                               36/60 
  Installing : 1:perl-Error-0.17020-2.el7.noarch                          37/60 
  Installing : perl-TermReadKey-2.30-20.el7.x86_64                        38/60 
  Installing : less-458-9.el7.x86_64                                      39/60 
  Installing : openssh-7.4p1-13.el7_4.x86_64                              40/60 
  Installing : cpp-4.8.5-16.el7.x86_64                                    41/60 
  Installing : libedit-3.0-12.20121213cvs.el7.x86_64                      42/60 
  Installing : openssh-clients-7.4p1-13.el7_4.x86_64                      43/60 
  Installing : kernel-headers-3.10.0-693.5.2.el7.x86_64                   44/60 
  Installing : glibc-headers-2.17-196.el7.x86_64                          45/60 
  Installing : glibc-devel-2.17-196.el7.x86_64                            46/60 
  Installing : gcc-4.8.5-16.el7.x86_64                                    47/60 
  Installing : python-backports-1.0-8.el7.x86_64                          48/60 
  Installing : python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch   49/60 
  Installing : python-setuptools-0.9.8-7.el7.noarch                       50/60 
  Installing : rsync-3.0.9-18.el7.x86_64                                  51/60 
  Installing : libstdc++-devel-4.8.5-16.el7.x86_64                        52/60 
  Installing : libgnome-keyring-3.12.0-1.el7.x86_64                       53/60 
  Installing : perl-Git-1.8.3.1-12.el7_4.noarch                           54/60 
  Installing : git-1.8.3.1-12.el7_4.x86_64                                55/60 
  Installing : gcc-c++-4.8.5-16.el7.x86_64                                56/60 
  Installing : python2-pip-8.1.2-5.el7.noarch                             57/60 
  Installing : gettext-0.19.8.1-2.el7.x86_64                              58/60 
install-info: No such file or directory for /usr/share/info/gettext.info.gz
  Installing : 1:make-3.82-23.el7.x86_64                                  59/60 
  Installing : bzip2-1.0.6-13.el7.x86_64                                  60/60 
  Verifying  : fipscheck-lib-1.4.1-6.el7.x86_64                            1/60 
  Verifying  : perl-HTTP-Tiny-0.033-3.el7.noarch                           2/60 
  Verifying  : libgnome-keyring-3.12.0-1.el7.x86_64                        3/60 
  Verifying  : python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch    4/60 
  Verifying  : perl-threads-shared-1.43-6.el7.x86_64                       5/60 
  Verifying  : 4:perl-Time-HiRes-1.9725-3.el7.x86_64                       6/60 
  Verifying  : libstdc++-devel-4.8.5-16.el7.x86_64                         7/60 
  Verifying  : libunistring-0.9.3-9.el7.x86_64                             8/60 
  Verifying  : git-1.8.3.1-12.el7_4.x86_64                                 9/60 
  Verifying  : perl-PathTools-3.40-5.el7.x86_64                           10/60 
  Verifying  : perl-threads-1.87-4.el7.x86_64                             11/60 
  Verifying  : 4:perl-macros-5.16.3-292.el7.x86_64                        12/60 
  Verifying  : gcc-4.8.5-16.el7.x86_64                                    13/60 
  Verifying  : fipscheck-1.4.1-6.el7.x86_64                               14/60 
  Verifying  : python-setuptools-0.9.8-7.el7.noarch                       15/60 
  Verifying  : groff-base-1.22.2-8.el7.x86_64                             16/60 
  Verifying  : gettext-libs-0.19.8.1-2.el7.x86_64                         17/60 
  Verifying  : rsync-3.0.9-18.el7.x86_64                                  18/60 
  Verifying  : 1:perl-parent-0.225-244.el7.noarch                         19/60 
  Verifying  : 4:perl-5.16.3-292.el7.x86_64                               20/60 
  Verifying  : bzip2-1.0.6-13.el7.x86_64                                  21/60 
  Verifying  : python2-pip-8.1.2-5.el7.noarch                             22/60 
  Verifying  : gettext-0.19.8.1-2.el7.x86_64                              23/60 
  Verifying  : perl-File-Temp-0.23.01-3.el7.noarch                        24/60 
  Verifying  : openssh-7.4p1-13.el7_4.x86_64                              25/60 
  Verifying  : 1:perl-Pod-Simple-3.28-4.el7.noarch                        26/60 
  Verifying  : perl-Time-Local-1.2300-2.el7.noarch                        27/60 
  Verifying  : libgomp-4.8.5-16.el7.x86_64                                28/60 
  Verifying  : openssh-clients-7.4p1-13.el7_4.x86_64                      29/60 
  Verifying  : perl-Pod-Perldoc-3.20-4.el7.noarch                         30/60 
  Verifying  : glibc-devel-2.17-196.el7.x86_64                            31/60 
  Verifying  : 1:perl-Error-0.17020-2.el7.noarch                          32/60 
  Verifying  : perl-Socket-2.010-4.el7.x86_64                             33/60 
  Verifying  : glibc-headers-2.17-196.el7.x86_64                          34/60 
  Verifying  : perl-Carp-1.26-244.el7.noarch                              35/60 
  Verifying  : perl-Git-1.8.3.1-12.el7_4.noarch                           36/60 
  Verifying  : gcc-c++-4.8.5-16.el7.x86_64                                37/60 
  Verifying  : 4:perl-libs-5.16.3-292.el7.x86_64                          38/60 
  Verifying  : python-backports-1.0-8.el7.x86_64                          39/60 
  Verifying  : perl-Storable-2.45-3.el7.x86_64                            40/60 
  Verifying  : perl-Scalar-List-Utils-1.27-248.el7.x86_64                 41/60 
  Verifying  : 1:make-3.82-23.el7.x86_64                                  42/60 
  Verifying  : libmpc-1.0.1-3.el7.x86_64                                  43/60 
  Verifying  : cpp-4.8.5-16.el7.x86_64                                    44/60 
  Verifying  : kernel-headers-3.10.0-693.5.2.el7.x86_64                   45/60 
  Verifying  : perl-Pod-Usage-1.63-3.el7.noarch                           46/60 
  Verifying  : perl-Encode-2.51-7.el7.x86_64                              47/60 
  Verifying  : perl-Exporter-5.68-3.el7.noarch                            48/60 
  Verifying  : perl-podlators-2.5.1-3.el7.noarch                          49/60 
  Verifying  : perl-Getopt-Long-2.40-2.el7.noarch                         50/60 
  Verifying  : perl-constant-1.27-2.el7.noarch                            51/60 
  Verifying  : perl-File-Path-2.09-2.el7.noarch                           52/60 
  Verifying  : perl-TermReadKey-2.30-20.el7.x86_64                        53/60 
  Verifying  : libedit-3.0-12.20121213cvs.el7.x86_64                      54/60 
  Verifying  : mpfr-3.1.1-4.el7.x86_64                                    55/60 
  Verifying  : perl-Filter-1.49-3.el7.x86_64                              56/60 
  Verifying  : perl-Text-ParseWords-3.29-4.el7.noarch                     57/60 
  Verifying  : libcroco-0.6.11-1.el7.x86_64                               58/60 
  Verifying  : less-458-9.el7.x86_64                                      59/60 
  Verifying  : 1:perl-Pod-Escapes-1.04-292.el7.noarch                     60/60 

Installed:
  bzip2.x86_64 0:1.0.6-13.el7            gcc-c++.x86_64 0:4.8.5-16.el7          
  gettext.x86_64 0:0.19.8.1-2.el7        git.x86_64 0:1.8.3.1-12.el7_4          
  make.x86_64 1:3.82-23.el7              python2-pip.noarch 0:8.1.2-5.el7       

Dependency Installed:
  cpp.x86_64 0:4.8.5-16.el7                                                     
  fipscheck.x86_64 0:1.4.1-6.el7                                                
  fipscheck-lib.x86_64 0:1.4.1-6.el7                                            
  gcc.x86_64 0:4.8.5-16.el7                                                     
  gettext-libs.x86_64 0:0.19.8.1-2.el7                                          
  glibc-devel.x86_64 0:2.17-196.el7                                             
  glibc-headers.x86_64 0:2.17-196.el7                                           
  groff-base.x86_64 0:1.22.2-8.el7                                              
  kernel-headers.x86_64 0:3.10.0-693.5.2.el7                                    
  less.x86_64 0:458-9.el7                                                       
  libcroco.x86_64 0:0.6.11-1.el7                                                
  libedit.x86_64 0:3.0-12.20121213cvs.el7                                       
  libgnome-keyring.x86_64 0:3.12.0-1.el7                                        
  libgomp.x86_64 0:4.8.5-16.el7                                                 
  libmpc.x86_64 0:1.0.1-3.el7                                                   
  libstdc++-devel.x86_64 0:4.8.5-16.el7                                         
  libunistring.x86_64 0:0.9.3-9.el7                                             
  mpfr.x86_64 0:3.1.1-4.el7                                                     
  openssh.x86_64 0:7.4p1-13.el7_4                                               
  openssh-clients.x86_64 0:7.4p1-13.el7_4                                       
  perl.x86_64 4:5.16.3-292.el7                                                  
  perl-Carp.noarch 0:1.26-244.el7                                               
  perl-Encode.x86_64 0:2.51-7.el7                                               
  perl-Error.noarch 1:0.17020-2.el7                                             
  perl-Exporter.noarch 0:5.68-3.el7                                             
  perl-File-Path.noarch 0:2.09-2.el7                                            
  perl-File-Temp.noarch 0:0.23.01-3.el7                                         
  perl-Filter.x86_64 0:1.49-3.el7                                               
  perl-Getopt-Long.noarch 0:2.40-2.el7                                          
  perl-Git.noarch 0:1.8.3.1-12.el7_4                                            
  perl-HTTP-Tiny.noarch 0:0.033-3.el7                                           
  perl-PathTools.x86_64 0:3.40-5.el7                                            
  perl-Pod-Escapes.noarch 1:1.04-292.el7                                        
  perl-Pod-Perldoc.noarch 0:3.20-4.el7                                          
  perl-Pod-Simple.noarch 1:3.28-4.el7                                           
  perl-Pod-Usage.noarch 0:1.63-3.el7                                            
  perl-Scalar-List-Utils.x86_64 0:1.27-248.el7                                  
  perl-Socket.x86_64 0:2.010-4.el7                                              
  perl-Storable.x86_64 0:2.45-3.el7                                             
  perl-TermReadKey.x86_64 0:2.30-20.el7                                         
  perl-Text-ParseWords.noarch 0:3.29-4.el7                                      
  perl-Time-HiRes.x86_64 4:1.9725-3.el7                                         
  perl-Time-Local.noarch 0:1.2300-2.el7                                         
  perl-constant.noarch 0:1.27-2.el7                                             
  perl-libs.x86_64 4:5.16.3-292.el7                                             
  perl-macros.x86_64 4:5.16.3-292.el7                                           
  perl-parent.noarch 1:0.225-244.el7                                            
  perl-podlators.noarch 0:2.5.1-3.el7                                           
  perl-threads.x86_64 0:1.87-4.el7                                              
  perl-threads-shared.x86_64 0:1.43-6.el7                                       
  python-backports.x86_64 0:1.0-8.el7                                           
  python-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el7                    
  python-setuptools.noarch 0:0.9.8-7.el7                                        
  rsync.x86_64 0:3.0.9-18.el7                                                   

Complete!

## Installing the NodeSource Node.js 6.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.bGQMeSOinO' 'https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.bGQMeSOinO'

## Cleaning up...

+ rm -f '/tmp/tmp.bGQMeSOinO'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## Run `yum install -y nodejs` (as root) to install Node.js 6.x and npm.
## You may also need development tools to build native addons:
##   `yum install -y gcc-c++ make`

Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: repo.apiknet.co.id
 * epel: mirror.nes.co.id
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:6.12.0-1nodesource will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package      Arch         Version                       Repository        Size
================================================================================
Installing:
 nodejs       x86_64       2:6.12.0-1nodesource          nodesource        13 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 13 M
Installed size: 38 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/nodesource/packages/nodejs-6.12.0-1nodesource.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 34fa74dd: NOKEY
Public key for nodejs-6.12.0-1nodesource.x86_64.rpm is not installed
Retrieving key from file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Importing GPG key 0x34FA74DD:
 Userid     : "NodeSource <gpg-rpm@nodesource.com>"
 Fingerprint: 2e55 207a 95d9 944b 0cc9 3261 5ddb e8d4 34fa 74dd
 Package    : nodesource-release-el7-1.noarch (installed)
 From       : /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : 2:nodejs-6.12.0-1nodesource.x86_64                           1/1 
  Verifying  : 2:nodejs-6.12.0-1nodesource.x86_64                           1/1 

Installed:
  nodejs.x86_64 2:6.12.0-1nodesource                                            

Complete!
make: *** No rule to make target `sdist'.  Stop.`

Still no luck, what I'm missed really?

**Comment by rizmut** [comment]
Ok I've copied all code block under 'How to build source archive', but still no luck.

`Complete!
make: *** No rule to make target ``sdist'.  Stop.`

**Comment by subuk** [comment]
Strange thing. I checked again and decided that previous version of readme worked better, so fixed it back and tried to build with copy-paste. Build was successfull.

Try to run each command separately and check what is wrong.

**Comment by rizmut** [comment]
OK I've retried it this day and it's successful, but I found in the `dist` directory contains `awx-1.0.1.229.tar.gz` whilst in [https://github.com/subuk/awx-rpm/releases](https://github.com/subuk/awx-rpm/releases) `1.0.1.225` is the latest version. Which one should be used?

**Comment by subuk** [comment]
You can use any. If you do not want the latest version of awx, just download it from awx-rpm/releases page, but if you want specific or latest version, you should build source tarball manually.

**Comment by rizmut** [comment]
Another error occurred, failed to build RPM file after placing all sources to `rpmbuild/SOURCES `


`ERROR   0001: file "/opt/awx/bin/uwsgi" contains a standard rpath "/usr/lib64" in [/usr/lib64]
error: Bad exit status from /var/tmp/rpm-tmp.5S3naO (%install)`


Any idea?

**Comment by rizmut** [comment]
For workaround, I set `QA_CHECKRPATHS=0` in my `~/.rpmmacros` file. Is this acceptable?

**Comment by seniormuffinman** [comment]
Hi!
I'm having the same problem @subuk. I tried following all the steps from the README but with no luck. I did not change the version as I think the default is right for me now.
I'm wondering if I did the right steps, not to criticize but I think the instructions need some rework, glad to help you in any way I can.

First attempt, using the `build.sh `script:

```
$  ./build.sh centos-7
/bin/sh: /build.sh: Permission denied

```

**Update**
SELinux problems ... got them fixed.
